name: Discord git updater thing

on:
  push:

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Send embed to Discord(hopefully)
        run: |
          REPO="${{ github.repository }}"
          AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          AVATAR_URL="${{ github.event.sender.avatar_url }}"
          BRANCH="${{ github.ref_name }}"

          JSON=$(jq -n \
            --arg title "New Update to $REPO" \
            --arg desc "$COMMIT_MSG" \
            --arg author "$AUTHOR" \
            --arg url "$COMMIT_URL" \
            --arg branch "$BRANCH" \
            --arg avatar "$AVATAR_URL" \
            --arg color "7506394" \
            '{
              embeds: [
                {
                  title: $title,
                  description: $desc,
                  color: ($color | tonumber),
                  url: $url,
                  author: { name: $author, icon_url: $avatar },
                  fields: [
                    { name: "Branch", value: $branch, inline: true },
                    { name: "Commit Link", value: "[View Commit](\($url))", inline: true }
                  ],
                  footer: { text: "GitHub updater thing" },
                  timestamp: (now | todate)
                }
              ]
            }')

          echo "$JSON" | jq .

          curl -H "Content-Type: application/json" \
               -d "$JSON" \
               "${{ secrets.DISCORD_WEBHOOK }}"
