name: Discord webhook thing guh

on:
  push:

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send update info to Discord
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          AUTHOR="${{ github.event.head_commit.author.name }}"
          URL="${{ github.event.head_commit.url }}"
          REPO="${{ github.repository }}"
          
          PAYLOAD=$(jq -n \
            --arg content " **New update to $REPO**\n **$AUTHOR** pushed:\n $COMMIT_MESSAGE\n <$URL>" \
            '{content: $content}')

          curl -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               ${{ secrets.DISCORD_WEBHOOK }}
        env:
          TZ: UTC
